---
# use firewalld as it is supported by ansible <=2.0
# run this role before using firewalld
#  to avoid issue https://github.com/ansible/ansible-modules-extras/issues/128

- name: install firewalld
  action: "{{ ansible_pkg_mgr }} state=installed name=firewalld"

- name: install missing packackage on fedoras
  action: "{{ ansible_pkg_mgr }} state=installed name=python-firewall"
  #when:  ( ansible_distribution == "Fedora" )

- name: start firewall
  service: name=firewalld enabled=yes state=started

